const books = [
  {
    titel: "Mysteriet på Björkbacken",
    forfattare: "Karin Svensson",
    formgivare: "Anna Andersson",
    upplaga: 2,
    ISBN: 9789123456789,
    sprak: "Svenska",
    vikt: "420 gram",
    serie: "(del 1)",
    utgiven: "2023-08-15",
    forlag: "Natur & Kultur",
    antalSidor: 280,
  },
  {
    titel: "Lost in Time Chronicles",
    forfattare: "Eva Andersson",
    formgivare: "Per Eriksson",
    upplaga: 1,
    ISBN: 9789198765432,
    sprak: "Engelska",
    vikt: "520 gram",
    serie: "(Book 1)",
    utgiven: "2023-09-20",
    forlag: "HarperCollins",
    antalSidor: 412,
  },
  {
    titel: "Hemligheterna i Skogen",
    forfattare: "Johan Karlsson",
    formgivare: "Sara Olsson",
    upplaga: 1,
    ISBN: 9789056781234,
    sprak: "Svenska",
    vikt: "300 gram",
    serie: "(del 1)",
    utgiven: "2023-07-01",
    forlag: "Bonnier Fakta",
    antalSidor: 200,
  },
  {
    titel: "Sagovärldens Mysterier",
    forfattare: "Anna Bergman",
    formgivare: "Oskar Persson",
    upplaga: 3,
    ISBN: 9789345678901,
    sprak: "Svenska",
    vikt: "450 gram",
    serie: "(del 1)",
    utgiven: "2023-11-10",
    forlag: "Albert Bonniers Förlag",
    antalSidor: 320,
  },
  {
    titel: "Stjärnornas Hemlighet",
    forfattare: "Oscar Lindgren",
    formgivare: "Lina Andersson",
    upplaga: 1,
    ISBN: 9789456789123,
    sprak: "Svenska",
    vikt: "380 gram",
    serie: "(del 1)",
    utgiven: "2023-12-05",
    forlag: "Wahlström & Widstrand",
    antalSidor: 240,
  },
  {
    titel: "Trädgårdsäventyret",
    forfattare: "Liselotte Eriksson",
    formgivare: "Per Persson",
    upplaga: 1,
    ISBN: 9789567890123,
    sprak: "Svenska",
    vikt: "550 gram",
    serie: "(del 1)",
    utgiven: "2023-10-18",
    forlag: "Semic",
    antalSidor: 380,
  },
  {
    titel: "Den Hemliga Porten",
    forfattare: "Andreas Nilsson",
    formgivare: "Sofia Karlsson",
    upplaga: 2,
    ISBN: 9789678901234,
    sprak: "Svenska",
    vikt: "500 gram",
    serie: "(del 1)",
    utgiven: "2023-08-28",
    forlag: "Norstedts Förlag",
    antalSidor: 310,
  },
  {
    titel: "Enchanted Forest Adventures",
    forfattare: "Sara Persson",
    formgivare: "Erik Eriksson",
    upplaga: 1,
    ISBN: 9789789012345,
    sprak: "Engelska",
    vikt: "420 gram",
    serie: "(Book 1)",
    utgiven: "2023-07-12",
    forlag: "Penguin Books",
    antalSidor: 270,
  },
  {
    titel: "Mysteriet vid Sjövik",
    forfattare: "Martin Karlsson",
    formgivare: "Emma Persson",
    upplaga: 1,
    ISBN: 9789901234567,
    sprak: "Svenska",
    vikt: "460 gram",
    serie: "(del 1)",
    utgiven: "2023-09-15",
    forlag: "Bokförlaget Forum",
    antalSidor: 350,
  },
  {
    titel: "Havets Hemlighet",
    forfattare: "Hanna Andersson",
    formgivare: "Olle Persson",
    upplaga: 1,
    ISBN: 9789090123456,
    sprak: "Svenska",
    vikt: "490 gram",
    serie: "(del 1)",
    utgiven: "2023-11-30",
    forlag: "Modernista",
    antalSidor: 400,
  },
];
